### ISSUE TITLE
Crash after adding R-N500

### ISSUE THREAD

**Issue by henkbb36org** [kruimel0/yamaha-app-homey#3]
App installs well but after adding my Yamaha R-N500 as device the app crashes:
Stack trace:

Error: connect EHOSTUNREACH 192.168.2.18:80
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

Exit code: 1
Exit signal: null

I entered the correct IP address of the  receiver and it is switched on. The app crashes after a couple of seconds and the device becomes unavailable. It worked before.

**Comment by kruimel0** [comment]
I just submitted version 0.2.1, which hopefully fixes this issue. Please report back if it does or not.

You can wait for it to be approved by athom, or use the CLI-method to install it earlier (read https://developers.athom.com/library/getting-started/ if you want to do this).

**Comment by henkbb36org** [comment]
Thanks for your response, greatly apprectiated. I installed 0.2.1 using the CLI-method. Unfortunately, it crashes again:
Stack trace:

TypeError: Cannot read property '1' of null
at Request.<anonymous> (/drivers/receiver/driver.js:433:37)
at emitOne (events.js:77:13)
at Request.emit (events.js:169:7)
at IncomingMessage.<anonymous> (/node_modules/request/request.js:965:12)
at emitOne (events.js:77:13)
at IncomingMessage.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:153:18)
at IncomingMessage.Readable.push (_stream_readable.js:111:10)
at HTTPParser.parserOnBody (_http_common.js:127:22)
at Socket.socketOnData (_http_client.js:322:20)

Exit code: 1
Exit signal: null

**Comment by kruimel0** [comment]
Thanks for the update. Just submitted version 0.2.2, can you check if that works for you?

**Comment by henkbb36org** [comment]
You're welcome :-) I installed 0.2.2,  I removed the device first but it crashed after adding it again, also after restarting homey and adding the device once more. The receiver is switched on, IP address correct for sure.

Stack trace:

TypeError: Cannot read property '1' of null
at Request.<anonymous> (/drivers/receiver/driver.js:445:27)
at emitOne (events.js:77:13)
at Request.emit (events.js:169:7)
at IncomingMessage.<anonymous> (/node_modules/request/request.js:965:12)
at emitOne (events.js:77:13)
at IncomingMessage.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:153:18)
at IncomingMessage.Readable.push (_stream_readable.js:111:10)
at HTTPParser.parserOnBody (_http_common.js:127:22)
at Socket.socketOnData (_http_client.js:322:20)

Exit code: 1
Exit signal: null

**Comment by kruimel0** [comment]
Thanks. Try v0.2.3 that I just uploaded. I think this should work.

**Comment by henkbb36org** [comment]
Yes, you fixed it, great work. Thank you!!

**Comment by kruimel0** [comment]
Good to hear! You're welcome!
